name: 'Docker CleanUp'
description: 'Kill all running docker container, and remove all docker volumes and docker networks'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: docker rm -f $(docker ps -aq) || echo "No docker containers to clean."

    - shell: bash
      run: docker network prune -f

    - shell: bash
      run: docker volume prune -f
